# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"

---
repositories:
  # openDesk Dovecot
  # Source: https://gitlab.opencode.de/bmi/souveraener_arbeitsplatz/components/charts/opendesk-dovecot
  - name: "opendesk-dovecot-repo"
    oci: true
    url: >-
      {{ env "PRIVATE_IMAGE_REGISTRY_URL" | default
         "external-registry.souvap-univention.de/sovereign-workplace/souvap/tooling/charts/dovecot" }}
    verify: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"
  # Open-Xchange
  - name: "openxchange-repo"
    oci: true
    url: >-
      {{ env "PRIVATE_IMAGE_REGISTRY_URL" | default "registry.open-xchange.com" }}
  # openDesk Open-Xchange Bootstrap
  # Source: https://gitlab.opencode.de/bmi/souveraener_arbeitsplatz/components/charts/opendesk-open-xchange-bootstrap
  - name: "opendesk-open-xchange-bootstrap-repo"
    oci: true
    # yamllint disable rule:line-length
    url: >-
      {{ env "PRIVATE_IMAGE_REGISTRY_URL" | default
         "external-registry.souvap-univention.de/sovereign-workplace/souvap/tooling/charts/sovereign-workplace-open-xchange-bootstrap" }}
    # yamllint enable rule:line-length
    verify: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"

releases:
  - name: "dovecot"
    chart: "opendesk-dovecot-repo/dovecot"
    version: "1.3.4"
    values:
      - "values-dovecot.yaml"
      - "values-dovecot.gotmpl"
    installed: {{ .Values.dovecot.enabled }}
    timeout: 900

  - name: "open-xchange"
    chart: "openxchange-repo/appsuite-public-sector/charts/appsuite-public-sector"
    version: "2.1.1"
    values:
      - "values-openxchange.yaml"
      - "values-openxchange.gotmpl"
      - "values-openxchange-enterprise-contact-picker.yaml"
      - "values-openxchange-enterprise-contact-picker.gotmpl"
    installed: {{ .Values.oxAppsuite.enabled }}
    timeout: 900

  - name: "opendesk-open-xchange-bootstrap"
    chart: "opendesk-open-xchange-bootstrap-repo/sovereign-workplace-open-xchange-bootstrap"
    version: "1.3.1"
    values:
      - "values-openxchange-bootstrap.gotmpl"
    installed: {{ .Values.oxAppsuite.enabled }}
    timeout: 900

commonLabels:
  deploy-stage: "component-1"
  component: "open-xchange"
...
