# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "dovecot"
    url: "https://gitlab.souvap-univention.de/api/v4/projects/80/packages/helm/stable"
  - name: "openxchange"
    url: "registry.open-xchange.com"
    oci: true
  - name: "sovereign-workplace-open-xchange-bootstrap"
    url: "https://gitlab.souvap-univention.de/api/v4/projects/139/packages/helm/stable"

releases:
  - name: "dovecot"
    chart: "dovecot/dovecot"
    version: "1.2.0"
    values:
      - "values-dovecot.yaml"
      - "values-dovecot.gotmpl"
    condition: "dovecot.enabled"
  - name: "open-xchange"
    chart: "openxchange/appsuite-public-sector/charts/appsuite-public-sector"
    version: "1.2.13"
    values:
      - "values-openxchange.yaml"
      - "values-openxchange.gotmpl"
    condition: "oxAppsuite.enabled"
  - name: "sovereign-workplace-open-xchange-bootstrap"
    chart: "sovereign-workplace-open-xchange-bootstrap/sovereign-workplace-open-xchange-bootstrap"
    version: "1.2.2"
    values:
      - "values-openxchange-bootstrap.yaml"
    condition: "oxAppsuite.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "open-xchange"

bases:
  - "../../bases/environments.yaml"
...
