# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
containerSecurityContext:
  readOnlyRootFilesystem: false

dovecot:
  ldap:
    enabled: true
    port: 389
    base: "dc=swp-ldap,dc=internal"

  oidc:
    enabled: true
    clientID: "as8oidc"
    usernameAttribute: "phoenixusername"
...
