# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"

---
repositories:
  # OX Connector
  - name: "ox-connector-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://gitlab.souvap-univention.de/api/v4/projects/128/packages/helm/stable" }}

releases:
  - name: "ox-connector"
    chart: "ox-connector-repo/ox-connector"
    version: "0.1.0-pre-jconde-listener-entrypoint-chaining"
    values:
      - "values-oxconnector.yaml"
      - "values-oxconnector.gotmpl"
    installed: {{ .Values.oxConnector.enabled }}

commonLabels:
  deploy-stage: "component-2"
  component: "provisioning"
...
