# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
bases:
  - "../../bases/environments.yaml"

---
repositories:
  # Collabora Online
  # Source: https://github.com/CollaboraOnline/online
  - name: "collabora-online-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://collaboraonline.github.io/online" }}

releases:
  - name: "collabora-online"
    chart: "collabora-online-repo/collabora-online"
    version: "1.0.2"
    values:
      - "values.yaml"
      - "values.gotmpl"
    installed: {{ .Values.collabora.enabled }}

commonLabels:
  deploy-stage: "component-1"
  component: "collabora"
...
