# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
# https://github.com/CollaboraOnline/online/blob/master/kubernetes/helm/README.md or
# https://github.com/CollaboraOnline/online/blob/master/kubernetes/helm/collabora-online/values.yaml

fullnameOverride: "collabora"

image:
  pullPolicy: "IfNotPresent"

collabora:
  extra_params: "--o:ssl.enable=false --o:ssl.termination=true"

securityContext:
  capabilities:
    add:
      - "MKNOD"

ingress:
  annotations:
    # nginx
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
    # HAProxy
    haproxy.org/timeout-tunnel: "3600s"
    haproxy.org/backend-config-snippet: |
     mode http
      balance leastconn
      stick-table type string len 2048 size 1k store conn_cur
      http-request set-var(txn.wopisrcconns) url_param(WOPISrc),table_conn_cur()
      http-request track-sc1 url_param(WOPISrc)
      stick match url_param(WOPISrc) if { var(txn.wopisrcconns) -m int gt 0 }
      stick store-request url_param(WOPISrc)

autoscaling:
  enabled: false
...
