# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
# https://github.com/CollaboraOnline/online/blob/master/kubernetes/helm/README.md or
# https://github.com/CollaboraOnline/online/blob/master/kubernetes/helm/collabora-online/values.yaml

fullnameOverride: "collabora"

image:
  pullPolicy: "IfNotPresent"

collabora:
  extra_params: "--o:user_interface.mode=tabbed --o:ssl.termination=true --o:ssl.enable=false"

ingress:
  annotations:
    # nginx
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
    # block admin and metrics endpoint from outside by default
    nginx.ingress.kubernetes.io/server-snippet: |
      location /cool/getMetrics { deny all; return 403; }
      location /cool/adminws/ { deny all; return 403; }
      location /browser/dist/admin/admin.html { deny all; return 403; }
    nginx.org/websocket-services: "collabora"
    nginx.org/lb-method: "hash $arg_WOPISrc consistent"

    # HAProxy
    haproxy.org/timeout-tunnel: "3600s"
    haproxy.org/backend-config-snippet: |
     mode http
      balance leastconn
      stick-table type string len 2048 size 1k store conn_cur
      http-request set-var(txn.wopisrcconns) url_param(WOPISrc),table_conn_cur()
      http-request track-sc1 url_param(WOPISrc)
      stick match url_param(WOPISrc) if { var(txn.wopisrcconns) -m int gt 0 }
      stick store-request url_param(WOPISrc)

    # HAProxy - Community: https://haproxy-ingress.github.io/
    haproxy-ingress.github.io/timeout-tunnel: 3600s
    haproxy-ingress.github.io/balance-algorithm: url_param WOPISrc check_post
     # block admin and metrics endpoint from outside by default
    haproxy-ingress.github.io/config-backend:
     hash-type consistent
     # block admin urls from outside
     acl admin_url path_beg /cool/getMetrics
     acl admin_url path_beg /cool/adminws/
     acl admin_url path_beg /browser/dist/admin/admin.html
     http-request deny if admin_url
autoscaling:
  enabled: false
...
