# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
postfix:
  relayNets: "10.0.0.0/8"
  virtualTransport: "lmtps:dovecot:24"
  smtpdSASLPath: "inet:dovecot:3659"
  smtpdMilters: "inet:clamav-milter:7357"
  hostname: "postfix"
  inetProtocols: "ipv4"
  smtpSASLAuthEnable: "yes"
  smtpSASLPasswordMaps: "lmdb:/etc/postfix/sasl_passwd.map"
  smtpUseTLS: "yes"
  smtpdSASLAuthEnable: "no"
  smtpdSASLSecurityOptions: "noanonymous"
  smtpdSASLType: "dovecot"
  smtpdUseTLS: "yes"
  smtpdTLSCertFile: "/etc/tls/tls.crt"
  smtpdKeyFile: "/etc/tls/tls.key"
  milterDefaultAction: "accept"
  rspamdHost: ""
  amavisHost: ""
  amavisPortIn: ""
...
