# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "bitnami"
    url: "https://charts.bitnami.com/bitnami"
  - name: "keycloak-theme"
    url: "https://gitlab.souvap-univention.de/api/v4/projects/96/packages/helm/stable"
  - name: "keycloak-extensions"
    url: "https://gitlab.souvap-univention.de/api/v4/projects/77/packages/helm/stable"

releases:
  - name: "keycloak-theme"
    chart: "keycloak-theme/sovereign-workplace-theme"
    version: "1.0.0"
    values:
      - "values-theme.gotmpl"
    condition: "keycloak.enabled"
  - name: "keycloak"
    chart: "bitnami/keycloak"
    version: "12.2.0"
    values:
      - "values-keycloak.gotmpl"
      - "values-keycloak.yaml"
      - "values-keycloak-idp.yaml"
    wait: true
    condition: "keycloak.enabled"
  - name: "keycloak-extensions"
    chart: "keycloak-extensions/keycloak-extensions"
    version: "0.1.0"
    needs:
      - "keycloak"
    values:
      - "values-extensions.yaml"
      - "values-extensions.gotmpl"
    condition: "keycloak.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "keycloak"

bases:
  - "../../bases/environments.yaml"
...
