# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "univention-corporate-container"
    url: "https://gitlab.souvap-univention.de/api/v4/projects/132/packages/helm/stable"

releases:
  - name: "univention-corporate-container"
    chart: "univention-corporate-container/univention-corporate-container"
    version: "1.0.10"
    values:
      - "values.yaml"
      - "values.gotmpl"
    condition: "univentionCorporateServer.enabled"

bases:
  - "../../bases/environments.yaml"
...
