# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "univention-corporate-container-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://gitlab.souvap-univention.de/api/v4/projects/132/packages/helm/stable" }}

releases:
  - name: "univention-corporate-container"
    chart: "univention-corporate-container-repo/univention-corporate-container"
    version: "1.0.10"
    values:
      - "values.yaml"
      - "values.gotmpl"
    condition: "univentionCorporateServer.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "univention-corporate-container"

bases:
  - "../../bases/environments.yaml"
...
