# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  # OpenProject
  # Source: https://github.com/opf/helm-charts
  - name: "openproject-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://charts.openproject.org" }}

releases:
  - name: "openproject"
    chart: "openproject-repo/openproject"
    version: "1.8.0"
    values:
      - "values.yaml"
      - "values.gotmpl"
    condition: "openproject.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "openproject"

bases:
  - "../../bases/environments.yaml"
...
