# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  # openDesk Element
  # Source: https://gitlab.souvap-univention.de/souvap/tooling/charts/sovereign-workplace-element
  - name: "opendesk-element-repo"
    oci: true
    # yamllint disable rule:line-length
    url: >-
      {{ env "PRIVATE_IMAGE_REGISTRY_URL" |
         default "external-registry.souvap-univention.de/sovereign-workplace/souvap/tooling/charts/sovereign-workplace-element" }}
    # yamllint enable rule:line-length
    verify: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"

  # openDesk Matrix Widgets
  # Source: https://gitlab.souvap-univention.de/souvap/tooling/charts/opendesk-matrix-widgets
  - name: "opendesk-matrix-widgets-repo"
    oci: true
    # yamllint disable rule:line-length
    url: >-
      {{ env "PRIVATE_IMAGE_REGISTRY_URL" |
         default "external-registry.souvap-univention.de/sovereign-workplace/souvap/tooling/charts/opendesk-matrix-widgets" }}
    # yamllint enable rule:line-length
    verify: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"

releases:
  - name: "opendesk-element"
    chart: "opendesk-element-repo/opendesk-element"
    version: "2.5.0"
    values:
      - "values-element.yaml"
      - "values-element.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "opendesk-well-known"
    chart: "opendesk-element-repo/opendesk-well-known"
    version: "2.5.0"
    values:
      - "values-well-known.yaml"
      - "values-well-known.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "opendesk-synapse-web"
    chart: "opendesk-element-repo/opendesk-synapse-web"
    version: "2.5.0"
    values:
      - "values-synapse-web.yaml"
      - "values-synapse-web.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "opendesk-synapse"
    chart: "opendesk-element-repo/opendesk-synapse"
    version: "2.5.0"
    values:
      - "values-synapse.yaml"
      - "values-synapse.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "opendesk-matrix-user-verification-service-bootstrap"
    chart: "opendesk-element-repo/opendesk-synapse-create-account"
    version: "2.5.0"
    values:
      - "values-matrix-user-verification-service-bootstrap.yaml"
      - "values-matrix-user-verification-service-bootstrap.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "opendesk-matrix-user-verification-service"
    chart: "opendesk-element-repo/opendesk-matrix-user-verification-service"
    version: "2.5.0"
    values:
      - "values-matrix-user-verification-service.yaml"
      - "values-matrix-user-verification-service.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "matrix-neoboard-widget"
    chart: "opendesk-matrix-widgets-repo/matrix-neoboard-widget"
    version: "3.1.0"
    values:
      - "values-matrix-neoboard-widget.yaml"
      - "values-matrix-neoboard-widget.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "matrix-neochoice-widget"
    chart: "opendesk-matrix-widgets-repo/matrix-neochoice-widget"
    version: "3.1.0"
    values:
      - "values-matrix-neochoice-widget.yaml"
      - "values-matrix-neochoice-widget.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "matrix-neodatefix-widget"
    chart: "opendesk-matrix-widgets-repo/matrix-neodatefix-widget"
    version: "3.1.0"
    values:
      - "values-matrix-neodatefix-widget.yaml"
      - "values-matrix-neodatefix-widget.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "matrix-neodatefix-bot-bootstrap"
    chart: "opendesk-element-repo/opendesk-synapse-create-account"
    version: "2.5.0"
    values:
      - "values-matrix-neodatefix-bot-bootstrap.yaml"
      - "values-matrix-neodatefix-bot-bootstrap.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

  - name: "matrix-neodatefix-bot"
    chart: "opendesk-matrix-widgets-repo/matrix-neodatefix-bot"
    version: "3.1.0"
    values:
      - "values-matrix-neodatefix-bot.yaml"
      - "values-matrix-neodatefix-bot.gotmpl"
    installed: {{ .Values.element.enabled }}
    timeout: 900

commonLabels:
  deploy-stage: "component-1"
  component: "element"

bases:
  - "../../bases/environments.yaml"
...
