# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "opendesk-element-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://gitlab.souvap-univention.de/api/v4/projects/148/packages/helm/stable" }}

releases:
  - name: "opendesk-element"
    chart: "opendesk-element-repo/opendesk-element"
    version: "2.0.1"
    values:
      - "values-element.yaml"
      - "values-element.gotmpl"
    condition: "element.enabled"

  - name: "opendesk-well-known"
    chart: "opendesk-element-repo/opendesk-well-known"
    version: "2.0.1"
    values:
      - "values-well-known.yaml"
      - "values-well-known.gotmpl"
    condition: "element.enabled"

  - name: "opendesk-synapse-web"
    chart: "opendesk-element-repo/opendesk-synapse-web"
    version: "2.0.1"
    values:
      - "values-synapse-web.yaml"
      - "values-synapse-web.gotmpl"
    condition: "element.enabled"

  - name: "opendesk-synapse"
    chart: "opendesk-element-repo/opendesk-synapse"
    version: "2.0.1"
    values:
      - "values-synapse.yaml"
      - "values-synapse.gotmpl"
    condition: "element.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "element"

bases:
  - "../../bases/environments.yaml"
...
