# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  # openDesk Jitsi
  # Source: https://gitlab.opencode.de/bmi/souveraener_arbeitsplatz/components/charts/opendesk-jitsi
  - name: "jitsi-repo"
    oci: true
    url: >-
      {{ env "PRIVATE_IMAGE_REGISTRY_URL" | default
         "external-registry.souvap-univention.de/sovereign-workplace/souvap/tooling/charts/sovereign-workplace-jitsi" }}
    verify: true
    keyring: "../../files/gpg-pubkeys/souvap-univention-de.gpg"

releases:
  - name: "jitsi"
    chart: "jitsi-repo/sovereign-workplace-jitsi"
    version: "1.7.1"
    values:
      - "values-jitsi.gotmpl"
    condition: "jitsi.enabled"
    timeout: 900

commonLabels:
  deploy-stage: "component-1"
  component: "jitsi"

bases:
  - "../../bases/environments.yaml"
...
