# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "intercom-service-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://gitlab.souvap-univention.de/api/v4/projects/66/packages/helm/stable" }}

releases:
  - name: "intercom-service"
    chart: "intercom-service-repo/intercom-service"
    version: "1.1.3"
    values:
      - "values.yaml"
      - "values.gotmpl"
    condition: "intercom.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "intercom-service"

bases:
  - "../../bases/environments.yaml"
...
