# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
umcGateway:
  showCookieBanner: true
  cookieBannerTitleDE: "Cookie Zustimmung"
  cookieBannerTitleEN: "Cookie Consent"
  cookieBannerTextDE: >-
    Die Nutzung dieses Angebots ist nur möglich, wenn Cookies gespeichert und
    verarbeitet werden können (essenzielle Cookies). Dafür benötigen wir Ihre
    Zustimmung. Bitte akzeptieren Sie um fortzufahren oder schließen Sie die
    Seite.
  cookieBannerTextEN: >-
    Usage of this site is only possible by storing and processing cookie
    information (essential cookies). We require your consent. Please accept to
    continue or close the page.

...
