{{/*
SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
SPDX-License-Identifier: Apache-2.0
*/}}
---

volumes:
  claims:
    shared-data: "shared-data-ums-ldap-server-0"
    shared-run: "shared-run-ums-ldap-server-0"

...
