# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---

service:
  type: "ClusterIP"

extraVolumes:
  - name: "opendesk-branding"
    configMap:
      name: "ums-stack-data-swp-branding"

extraVolumeMounts:
  - name: "opendesk-branding"
    mountPath: "/app/favicon.ico"
    subPath: "favicon.ico"
  - name: "opendesk-branding"
    mountPath: "/app/univention/portal/css/custom.css"
    subPath: "custom.css"
  - name: "opendesk-branding"
    mountPath: "/app/univention/portal/icons/logo.svg"
    subPath: "logo.svg"
  - name: "opendesk-branding"
    mountPath: "/app/univention/portal/icons/logo_small_border.svg"
    subPath: "logo_small_border.svg"
  - name: "opendesk-branding"
    mountPath: "/app/univention/portal/custom/portal_background_image.png"
    subPath: "portal_background_image.png"
  - name: "opendesk-branding"
    mountPath: "/app/univention/portal/custom/portal_background_image.svg"
    subPath: "portal_background_image.svg"

...
