# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "xwiki"
    url: "https://xwiki-contrib.github.io/xwiki-helm"
  - name: "xwiki-init"
    url: "https://gitlab.souvap-univention.de/api/v4/projects/136/packages/helm/stable"

releases:
  - name: "xwiki"
    chart: "xwiki/xwiki"
    version: "1.1.0"
    wait: true
    timeout: 600
    values:
      - "values.yaml"
      - "values.gotmpl"
    condition: "xwiki.enabled"
  - name: "xwiki-init"
    chart: "xwiki-init/xwiki-init"
    version: "1.2.0"
    needs:
      - "xwiki"
    values:
      - "values-init.gotmpl"
    condition: "xwiki.enabled"
bases:
  - "../../bases/environments.yaml"
...
