# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  - name: "xwiki-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://xwiki-contrib.github.io/xwiki-helm" }}

releases:
  - name: "xwiki"
    chart: "xwiki-repo/xwiki"
    version: "1.1.2"
    wait: true
    timeout: 600
    values:
      - "values.yaml"
      - "values.gotmpl"
    condition: "xwiki.enabled"

commonLabels:
  deploy-stage: "component-1"
  component: "xwiki"

bases:
  - "../../bases/environments.yaml"
...
