# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
repositories:
  # XWiki
  # Source: https://github.com/xwiki-contrib/xwiki-helm
  - name: "xwiki-repo"
    url: >-
      {{ env "PRIVATE_CHART_REPOSITORY_URL" |
         default "https://xwiki-contrib.github.io/xwiki-helm" }}

releases:
  - name: "xwiki"
    chart: "xwiki-repo/xwiki"
    version: "1.2.3"
    wait: true
    values:
      - "values.yaml"
      - "values.gotmpl"
    installed: {{ .Values.xwiki.enabled }}
    timeout: 900

commonLabels:
  deploy-stage: "component-1"
  component: "xwiki"

bases:
  - "../../bases/environments.yaml"
...
