# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
## The global properties are used to configure multiple charts at once.
#
global:

  ## Define ingress/virtualservice host.
  #
  hosts:
    collabora: "collabora"
    dimension: "integration"
    element: "chat"
    etherpad: "etherpad"
    intercomService: "ics"
    jitsi: "meet"
    keycloak: "id"
    matrixNeoBoardWidget: "matrix-neoboard-widget"
    matrixNeoChoiceWidget: "matrix-neochoice-widget"
    matrixNeoDateFixWidget: "matrix-neodatefix-widget"
    meetingWidgetsBot: "meeting-widgets-bot"
    nextcloud: "fs"
    openproject: "project"
    openxchange: "webmail"
    openxchangeProvisioning: "ox-provisioning"
    synapse: "matrix"
    univentionCorporateServer: "portal"
    univentionManagementStack: "portal"
    whiteboard: "whiteboard"
    xwiki: "wiki"


  ## Define docker registry address.
  #
  imageRegistry: "external-registry.souvap-univention.de/sovereign-workplace"

  ## Credentials to fetch images from private registry
  ## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  #
  imagePullSecrets:
    - "external-registry"

  ## Define the policy to pull container images.
  ## Ref: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  #
  imagePullPolicy: "IfNotPresent"
...
