# SPDX-FileCopyrightText: 2023 Bundesministerium des Innern und für Heimat, PG ZenDiS "Projektgruppe für Aufbau ZenDiS"
# SPDX-License-Identifier: Apache-2.0
---
persistence:
  enabled: true
  existingClaim: "nextcloud-main"
  nextcloudData:
    enabled: true
    existingClaim: "nextcloud-data"

redis:
  enabled: false

cronjob:
  enabled: true
  lifecycle:
    postStartCommand:
      - "sh"
      - "-c"
      - >
        sed -i "s/\*\/5 \* \* \* \* php -f \/var\/www\/html\/cron.php/\*\/1 \* \* \* \* php -f
        \/var\/www\/html\/cron.php/g" /var/spool/cron/crontabs/www-data

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4G"
    nginx.org/client-max-body-size: "4G"

internalDatabase:
  enabled: false
postgresql:
  enabled: false
mariadb:
  enabled: false
externalDatabase:
  enabled: true
  # The nextcloud helm chart provides a sub-chart for mariadb.
  # If we use mariadb as a sub-chart it's linked to nextcloud,
  # and it is not independent anymore. Since externalDatabase.type
  # allows just mysql or postgres, mysql is chosen to connect
  # to the mariadb:
  type: "mysql"

nextcloud:
  configs:
    mimetypealiases.json: |-
      {
        "application/x-drawio": "image"
      }

    mimetypemapping.json: |-
      {
        "drawio": ["application/x-drawio"]
      }

# this is not documented but can be found in values.yaml
service:
  port: "80"
